### ISSUE TITLE
Issues with 2FA when signing transactions.

### ISSUE THREAD

**Issue by pygeek** [LedgerHQ/ledger-wallet-chrome#10]
I have encountered several attempts to sign transactions using the iPhone ledger app recently. Here are issues I've encountered while attempting to sign different transactions:
1. If the mobile app is not in the foreground, a notification is presented, but when tapping on the notification to reveal the application, there is no prompt to authorize the transaction. I have to cancel the transaction from my desktop machine and try again with the ledger mobile app in the foreground.
2. If the mobile app is in the foreground, I get a prompt to authorize the transaction, but upon authorizing the transaction and receiving a success message on my desktop machine, the transaction does not seem to be present.
3. When attempting to sign a transaction from my desktop machine, the signing process hangs before attempting the 2FA.

**Comment by nicolasbigot** [comment]
"the transaction does not seem to be present": you mean the transaction does not seem to be pushed to the Bitcoin network (not present on any blockchain explorer)?
