### ISSUE TITLE
Bitcoin Private app on Nano S stuck on "Opening your wallet" on first launch.

### ISSUE THREAD

**Issue by tinkermade** [LedgerHQ/ledger-wallet-chrome#102]
Bitcoin Private app on Nano S only spins when I try to open it for the first time.  I let it spin 4 minutes at "Opening your wallet this could take a few minutes", then disconnected it and tried again.  I only have BTC, ETH, and BTCP apps installed.  Tried to install BTCP app first but it failed, error said to install BTC app first, which I did.

Troubleshooting:
- Unplugged and reconnected
- delete app and re-add

Ledger firmware version: 
- Secure Element 1.4.2
- MCU 1.5

Bitcoin Private version: 1.2.5

**Comment by amougel** [comment]
The ledger-wallet-chrome chrome app from Ledger does not and will not support BTCP. A third party wallet integration is currently under development https://github.com/BTCPrivate/electrum-btcp/releases/.
