### ISSUE TITLE
Add an initialization script in order to install nodejs dependencies

### ISSUE THREAD

**Issue by ehteqx** [LedgerHQ/ledger-wallet-chrome#17]
After following the proposed installation instructions on my setup (Ubuntu 14.04 LTS with a NodeJS fresh install) I was unable to compile the *.crx file, before manually installing as dependencies all the required packages with npm.

A proposed solution could be to implement a simple shell script (at least for Linux, I don't know if the problem still applies to Windows or MacOS) to initialize the build system before starting the building process.

The attached file is an example. 

EDIT: I am not able to attach a *.sh file. It can be fetched from my fork: https://github.com/ehteqx/ledger-wallet-chrome/blob/master/initialize.sh

**Comment by pollastri-pierre** [comment]
Normally running "npm install" at the root of the project should install these dependencies.  I don't see why it didn't work for you.
