### ISSUE TITLE
Remember device feature. (see balances and receiving addresses while device is not connected)

### ISSUE THREAD

**Issue by Transisto** [LedgerHQ/ledger-wallet-chrome#18]
I think that was a feature with the old Nano, I can't figure out how to enable this with the Nano S.

**Comment by nicolasbigot** [comment]
Can you be more specific? What do you mean by "remember the device"?

**Comment by Transisto** [comment]
What I mean is being able to "(see balance and receiving addresses.)" when device is not present.

**Comment by pollastri-pierre** [comment]
Right now this not possible, this feature is planned for Ledger Wallet 2.0 and our mobile applications. if you want such feature currently you will need to use a third party service like Sentinel (https://play.google.com/store/apps/details?id=com.samourai.sentinel) or Goochain (https://goochain.net/).

**Comment by Transisto** [comment]
Thank you for your response. The wallets I use with the NanoS with already have this feature (Mycelium & Electrum).
