### ISSUE TITLE
Support or Sweep from popular alternative BIP32 paths

### ISSUE THREAD

**Issue by ChristopherA** [LedgerHQ/ledger-wallet-chrome#25]
Breadwallet (and I think Copay) mobile wallets appear to use an alternative BIP32 path (reportedly m/0'/0/0). If I use share my recovery phrase between them they see the funds and change (great for testing).

However, when I set up my ledger to use my recovery phrase from Breadwallet/Copy, and after recovery the Ledger doesn't see the funds that are also held by that root.

You maybe should look during the first use of wallet at some popular paths and either warn users (who might think their funds are lost), and either allow the user to sweep into your BIP44 paths, or support the alternative paths of popular wallets for at least spending any addresses with amounts until they are all empty.

**Comment by pollastri-pierre** [comment]
Thank you for your feedback, we will probably add this kind of feature in the future. Right now we are preparing new tools and libraries to work on Ledger Wallet 2.0 (standalone) application. Since we are a small team, this kind of feature will be released lately.
