### ISSUE TITLE
Litecoin

### ISSUE THREAD

**Issue by briannyeko** [LedgerHQ/ledger-wallet-chrome#26]
When will you create a separate Ledger Litecoin Wallet app?

**Comment by pollastri-pierre** [comment]
Hello,

We are working to create a new application which will handle every crypto currency that we are currently supporting (Bitcoin, Litecoin, Zcash, Dogecoin, Dash, ETH, ETC). In the meantime Bitcoin based currencies will be managed by the bitcoin wallet.
