### ISSUE TITLE
Chrome apps will be deprecated on Windows, Mac, Linux

### ISSUE THREAD

**Issue by antonizoon** [LedgerHQ/ledger-wallet-chrome#29]
Google strongly advises developers to begin migrating away from using chrome apps and use native or browser based apps instead...

https://blog.chromium.org/2016/08/from-chrome-apps-to-web.html?m=1

**Comment by pollastri-pierre** [comment]
We are currently working on new native application for Windows, MacOS and Linux that should be release sometime around september.

**Comment by arkan** [comment]
Any update about that?
