### ISSUE TITLE
Send to many

### ISSUE THREAD

**Issue by blockonomics** [LedgerHQ/ledger-wallet-chrome#31]
Is this already on the roadmap, or any specific reason why this hasn't been implemented yet. Send to many has several advantages in current high tx fee scenario. Also an ability to upload a csv of address, amount to send would be preferable (like electrum).

**Comment by pollastri-pierre** [comment]
We are working on a new desktop application which will have more features. We have planned to had this feature in the new app. We are not working on new feature on this application in order to focus on the new one.
