### ISSUE TITLE
remove/adjust minimum 100 satoshis per byte fee

### ISSUE THREAD

**Issue by thedavidmeister** [LedgerHQ/ledger-wallet-chrome#33]
https://bitcoinfees.21.co/ is showing transactions going through in the 60-90 satoshis per byte range, and if the BTC price keeps going up I'd expect this number to drop.

**Comment by thedavidmeister** [comment]
blockchain.info is recommending 78 satoshis per byte for a "regular" transaction atm

**Comment by pollastri-pierre** [comment]
We are changing this behaviour to a minimum of 10 satoshi. We are already using https://bitcoinfees.21.co/ so the minimum fees when you choose from fast, normal, slow can already be lower than 100. We used 100 satoshi to avoid users locking their wallet to pay less fees.

**Comment by thephez** [comment]
@pollastri-pierre I assume this will this apply to the other coins that operate via the same application (Litecoin, Dash, etc.), correct?  Some of them still work with fees of zero.  I would be nice to have an advanced mode to allow manual fee entry, although I know that could end up creating unnecessary support issues.

**Comment by thedavidmeister** [comment]
Why would you even have an opinion on what fees ledger owners choose to add to their transactions under the "custom fees" option?

If you simply _must_ have an opinion, why not set a _dynamic_ lower limit based on https://bitcoinfees.21.co/ (set it to the first bracket that has infinite transaction time or something) rather than hard coding something static?

I still think that even if you change that limit something isn't right here based on what you're saying.

IIRC Bitcoin Fees is showing transactions going through (albeit slowly) as low as 61-90 satoshis per byte:

<img width="1205" alt="screen shot 2017-06-13 at 12 58 58 am" src="https://user-images.githubusercontent.com/629710/27040376-2259491a-4fd4-11e7-9e90-b71cc51d7243.png">

My UI for "slow" is showing $3.05 AUD (~220 satoshis per byte) for a 0.02BTC transaction, which is way higher than the "normal" fees that blockchain.info was charging tonight (remember, i mentioned these were sitting at 78) and still quite a bit higher than the 100 satoshis static limit that you're saying "slow" should be able to automatically drop below when it makes sense to.

For reference, setting a custom fee of 80 satoshis per byte (i cannot submit the form) for the same 0.02BTC transaction shows transaction fees of $1.12 per transaction.

**Comment by pollastri-pierre** [comment]
@thephez right now we won't support custom fees for other currencies than bitcoin. This application will soon be deprecated and we are only working to maintain the application usable. The custom fee option is only available for currencies with a fee per byte policy (so basically only bitcoin).

@thedavidmeister like I said the minimum amount for custom fees will be changed to 10 satoshi per byte. For the chrome application slow means that the transaction will be mined within 6 blocks (~1 hour). So from your graphic the fee should be around 211 and 240 satoshi per byte.

**Comment by thedavidmeister** [comment]
@pollastri-pierre maybe an "extra slow" option might be nice, i'm happy to wait a fair bit more than 1 hour to slash more than half the transaction fees off.

**Comment by Praethiax** [comment]
push.
Would be really nice to have this option to set custom amounts.
Currently i'm not using my Ledger for smal transaction because of that.

**Comment by shivaenigma** [comment]
I agree with @thedavidmeister 

> Why would you even have an opinion on what fees ledger owners choose to add to their transactions under the "custom fees" option?

Custom fee already means the user knows what he is doing. I am happy to wait even 10 days for the transaction to confirm (and most it will get confirmed during weekend).  Understand the bitcoinfees data is wrong lots of times, tx confirm much faster/slower than that.  

I am totally frustrated when the custom fee option doesn't allow me to set less than 100 S/B. Wanted to manually go and sign inputs. Even min of 10 S/B is unacceptable. That is just wrong UI (you already have other options for system recommend fee). Custom fee itself means you should let the user decide !  Max you should do is give a warning saying this will be slow (like blockchain.info)

**Comment by thedavidmeister** [comment]
I'm frustrated that there is no ETA or update from Ledger on this issue in 7 days, so I still have no idea when I can expect to make the transactions that I want to in an affordable way.

I'm frustrated that Ledger hasn't explained their (seemingly arbitrary?) reasoning behind the need for any limit at all.

I'm frustrated that the proposed solution is obviously not future proof, but there's no discussion of future plans from Ledger.

**Comment by Seccour** [comment]
@thedavidmeister They still put the 100 sat / bytes limit under the custom fees options because they are still some (really) stupid users that use this option without knowing what they are doing. And go then complain on the Ledger support about their blocked txs. So to avoid too much support ticket they have put this minimum.

**Comment by thedavidmeister** [comment]
@Seccour that seems like a rather nuclear response to such a basic UX problem (remember all the hoops a user has jumped through thus far to get to this point, they can obviously follow _some_ instructions), also that is only what you're _assuming_ is the rationale behind this, not what any rep from Ledger has said, which so far is only:

> We used 100 satoshi to avoid users locking their wallet to pay less fees.

That statement has nothing to do with avoiding support costs.

**Comment by pollastri-pierre** [comment]
@thedavidmeister In fact we spoke about this issue on reddit, and this is true we put the limit to avoid overloading our support. People are using custom fees and then complains about it on uspport because their transactions are stuck for a week. But this debate is closed, we are releasing the application today.

**Comment by thedavidmeister** [comment]
@pollastri-pierre thanks for the update, really glad to hear there's a new version coming out soon!

I'm not accustomed to cross referencing github issues against reddit threads, so I missed out on that debate :(

In my mind this is the Venn diagram of users who would continue to contact support with a simple addition of some help text on the UI form:

<img width="582" alt="screen shot 2017-06-20 at 6 45 59 pm" src="https://user-images.githubusercontent.com/629710/27324493-bd8e3480-55e8-11e7-86d3-61489e0efaa4.png">

Obviously I can be wrong about such things though as I haven't met any of these users clogging up the support lines.

**Comment by shivaenigma** [comment]
> @thedavidmeister In fact we spoke about this issue on reddit, and this is true we put the limit to avoid overloading our support. People are using custom fees and then complains about it on uspport because their transactions are stuck for a week. But this debate is closed, we are releasing the application today.

I doubt you have more support requests than blockchain.info which already implemented this beautiful interface where you can specify any custom fee
https://www.reddit.com/r/Bitcoin/comments/6jgsi4/blockchaininfo_updated_their_wallet_fee_interface/

Time to move to Trezor !

**Comment by pollastri-pierre** [comment]
We also have this feature, and for the record we have less funds/employees than blockchain.info. It's way easier for them to include feature that brings support tickets without killing their support.
We are scaling our teams at the moment in order to be able to bring more and more advanced features and better performances/UX but for the moment we are trying to keep the service working without killing our support. But we have great projects which should be released during Q4.

https://techcrunch.com/2017/06/22/the-company-called-blockchain-raises-40-million/

**Comment by shivaenigma** [comment]
@pollastri-pierre  when is the version allowing 10 S/B coming out in the store. Current version is 1.7.0 which is still stuck at 100 S/B

**Comment by pollastri-pierre** [comment]
@shivaenigma the 1.7.0 allows you to put 0 S/B in the custom fees field. FYI I just sent a transaction with 1 S/B with the freshly installed chrome application from the store.

https://blockchain.info/tx/9833b2cd839a8b4fcd299dcb6d73ccc6ef648aa98760a5c4fbe369f8889b958a

**Comment by shivaenigma** [comment]
@pollastri-pierre  Thanks ! Works now. Seems like some caching issue
