### ISSUE TITLE
Error when submitting transaction

### ISSUE THREAD

**Issue by jaspervdm** [LedgerHQ/ledger-wallet-chrome#34]
Hello,
I am trying to perform a BTC transaction with the Chrome app. When I press "Send", a loading bar appears for a second, after which the following error appears: http://imgur.com/diQeX3B

On the device I get the standard choice to allow or deny the transaction, however when I allow it the Chrome app just closes and goes back to the screen that says "To begin, connect and unlock your Ledger Wallet". I then have to restart the app and browser to go back to the overview.

In the log file I see the following message:
```
Mon, 19 Jun 2017 21:23:23 GMT,INFO,Router,Routing to [/wallet/accounts/index#send]
Mon, 19 Jun 2017 21:23:23 GMT,INFO,Transaction,--- CREATE TRANSACTION ---
Mon, 19 Jun 2017 21:23:23 GMT,INFO,Transaction,Amount:  6043600
Mon, 19 Jun 2017 21:23:23 GMT,INFO,Transaction,Fees:  45400
Mon, 19 Jun 2017 21:23:23 GMT,INFO,Transaction,Total send:  108337904
Mon, 19 Jun 2017 21:23:23 GMT,INFO,Transaction,Address:  3*****f
Mon, 19 Jun 2017 21:23:23 GMT,INFO,Transaction,UTXO:  << stringify error: TypeError: Converting circular structure to JSON >>
Mon, 19 Jun 2017 21:23:23 GMT,INFO,Transaction,Change path:  44'/0'/0'/1/3
Mon, 19 Jun 2017 21:23:23 GMT,INFO,Transaction,Data:  undefined
```
I am using the latest firmware and wallet version. Could you look into this error? Thank you.

**Comment by pollastri-pierre** [comment]
Hello,

I will need the complete logs in order to understand the issue (the part you gave me is normal, it just describes the transaction you are trying to do. The "stringify error" may seems odd but this is "normal").

**Comment by jaspervdm** [comment]
Is it safe for me to post the contents of `ledger_wallet_private_logs_20170619.csv`? I wouldn't want to expose any of my private data etc

**Comment by pollastri-pierre** [comment]
You shouldn't post the logs here because you will expose all your used addresses to everybody. Send the logs to support@ledgerwallet.com, and put "Pierre" somewhere in your email so I can check it quickly.

**Comment by jaspervdm** [comment]
Okay, thank you. I just sent them
