### ISSUE TITLE
Settings are lost when switching chains

### ISSUE THREAD

**Issue by zargony** [LedgerHQ/ledger-wallet-chrome#38]
Settings like fiat currency, number of confirmations and standard transaction fee are lost when switching chains. List of transactions seem to mix up / went missing as well.

How to reproduce:
- start app (select the standard Bitcoin blockchain on first start)
- connect Ledger Nano S
- make sure that settings are set e.g. to currency EUR, 3 confirmations, normal confirmation fee.
- use settings->blockchain to switch to Bitcoin Cash blockchain (optionally restart Ledger Wallet Bitcoin)
- settings are now back to USD, confirmations are set to 1 and fee is set to high
- use settings->blockchain to switch back to standard Bitcoin
- settings are still USD, 1 confirmation, high fee

Sometimes, language and region get also reset to something strange (I'm using German/Germany usually).
The list of transactions seems to get messed up as well. Switching to BCC removes all transactions that were done after the fork (which seems correct), but when switching back to BTC, they don't appear again.

Using settings->tools->reset makes everything working again (until you switch the chain again)

**Comment by btchip** [comment]
We know about it, the team is working on a fix

**Comment by btchip** [comment]
Fixed in 1.8.4

**Comment by zargony** [comment]
Works fine now, thanks!
