### ISSUE TITLE
'package' and 'zip' gulp tasks do not complete

### ISSUE THREAD

**Issue by djpnewton** [LedgerHQ/ledger-wallet-chrome#43]
Below is the output I am getting (the package task never finished and there is no crx file generated) 

> ~/projects/ledger-wallet-chrome$ gulp clean build package -n testnet --release
>[13:15:51] Using gulpfile ~/projects/ledger-wallet-chrome/gulpfile.js
>[13:15:51] Starting 'clean'...
>[13:15:51] Starting 'build'...
>[13:15:51] Starting 'package'...
>[13:15:51] Finished 'clean' after 170 ms
>[13:16:03] Finished 'build' after 12 s

**Comment by pollastri-pierre** [comment]
Thanks for the report we know this bug but didn't have time to look at it. I let this issue open until we solve it.

**Comment by kosciej** [comment]
I've got the same issue.

Gulp version:
CLI version 3.9.1
Local version 3.9.1

NodeJs version: v8.8.1

**Comment by diffusae** [comment]
Me too ..

nodejs v4.2.6

**Comment by PaulRBerg** [comment]
Same problem here. Sorry, I've opened another issue #59. Don't you guys get that error when you try to zip?

**Comment by pollastri-pierre** [comment]
Yes we have the same bug, we didn't have time to look at it yet.

**Comment by kosciej** [comment]
How you build release version currently?
W dniu wt., 7.11.2017 o 14:21 Pierre Pollastri <notifications@github.com>
napisał(a):

**Comment by pollastri-pierre** [comment]
gulp clean build --release

and then we zip the build directory. I'll see to fix this for the next release.

**Comment by pollastri-pierre** [comment]
I fixed this issue (https://github.com/LedgerHQ/ledger-wallet-chrome/commit/46f37f016bdd286dcd4e3f50e44e99a25c025612). It will be available on master tomorrow (once we release stealthcoin and some fixes on CPFP)
