### ISSUE TITLE
Accelerate confirmation window shows errors in numbers where there are none

### ISSUE THREAD

**Issue by menkaur** [LedgerHQ/ledger-wallet-chrome#50]
When you edit custom fees in the Accelerate confirmation window, what you often get is something like this;

![image](https://user-images.githubusercontent.com/171994/30511948-600aab60-9aec-11e7-8992-709184d05420.png)

25 is a good number, but for some reason, the window shows it as a mistake

**Comment by takeratta** [comment]
+1

**Comment by pollastri-pierre** [comment]
Normally the number is writted in red if the transaction you are trying to accelerate has a greater or equal amount of satoshi per byte
