### ISSUE TITLE
Sending is failing when using 1satoshi/byte

### ISSUE THREAD

**Issue by shivaenigma** [LedgerHQ/ledger-wallet-chrome#52]
**How to reproduce**
Send bitcoin using custom fee 1 S/B
**Result**
Sending failed - An error occurred. Please try again later
**Environment**
- Chrome extension version 1.9.4
- Ledger OS 1.0.2 
- Bitcoin Chain (No Segwit)

This should be supported as even 0 satoshi/bytes tx are [confirming](https://core.jochen-hoenicke.de/queue/#24h)

**Comment by pollastri-pierre** [comment]
Your transaction was rejected by the Bitcoin-core node, there is nothing we can do to prevent it.

**Comment by shivaenigma** [comment]
What do you mean you cannot prevent it ? I am assuming it sends the tx to a bitcoin node controlled by you. You can set the transaction minrelaytxfee on your node.

**Comment by pollastri-pierre** [comment]
We are using the default configuration which prevents using a too low fees when the mempool is to loaded. If the mempool is low when you create your transaction, even a 0 fee transaction will pass through. If the mempool has already a lot of transactions, you transaction will be rejected.
