### ISSUE TITLE
Use without Chrome

### ISSUE THREAD

**Issue by filips123** [LedgerHQ/ledger-wallet-chrome#55]
Add support to use Ledger wallet without Chrome.

**Comment by shakasan** [comment]
Add Firefox support
- FF57+ support WebExtensions
- FF57+ support U2F natively
- FF58 nightly is incredibly smooth, fast and pleasant to use. No doubt that FF is back !

The FF support is the last point that prevent me to take a nano s ;-)

Thanks

**Comment by pollastri-pierre** [comment]
We won't make a chrome application for FF. We are currently working on new application which doesn't rely on a browser to work.

**Comment by shakasan** [comment]
Thanks for your reply and it sounds good :-)
This application will run natively on Linux systems like Linux Mint/Ubuntu/Debian ?
Thanks :-)

**Comment by pollastri-pierre** [comment]
Yes it will work on Linux for sure. The only downside is that we will drop Chrome OS support (chrome users will have to use the future Android application if their hardware is compatible)

**Comment by shakasan** [comment]
Or install a real Linux system on their Chromebook ;-)
Ok, sounds very good. I can't wait ^^
