### ISSUE TITLE
[error] $BTC  in Ledger nano S couldn't to be sent other blockchain address, error occure and say  "sending error later try!" 

### ISSUE THREAD

**Issue by takeratta** [LedgerHQ/ledger-wallet-chrome#63]
To Dear Dev. team,

Now closing at Ledger's Slack for security reason, It's sad, 
So please I want to check this issue.

(If can, please announce LedgerHQ's security issues to the products' users.)

several problems I found : 

problem 1 : 
I sent a few BTC from bitFlyer : (a Crypto-Exchanger company  in Japan.) 

My Ledger nano S's address using my newest version Chrome extension's Ledger Chrome wallet for Bitcoin & Altcoins, 
but sending error occured. 
>(Pop-up alart say "sending error : Leter try" in Japanese language. / `送信失敗 後ほど再試行してください。`)

problem 2 : 
I send my BTC withdrawal to my Ledger nano S from My bifFlyer's withdraw BTC address.
My Chrome extension Ledger Chrome Wallet received successly, 

But `Sender Name` showed wrong Exchanger name in everytime from bitFlyer
 : it displayed "from `Coinbase`" name.
Why Coinbase ? 
I haven't any `coinbase `account. I guess issue #56 would has the key.

I thought wallet name table unmatch happening.
I tried to fix some problems, but I can't find Ledger wallet, API, node, in GitHub.
There are no codes directly connecting these error.

~~I thoght they could occure probable In LedgerHQ's on-premise in house codes, ~~
~~Not Open-Source some codes perhaps could need to fix up.~~
~~or private repositories in LedgerHQ.~~
>If not, I apporozised all of Dev. team members.

The other side, I found Twitter account : @LedgerHQ tweeted : 
[https://twitter.com/LedgerHQ/status/928573656283967488](https://twitter.com/LedgerHQ/status/928573656283967488)
>"OVH infrastructure is coming up. Our server infrastructure is now fully functionnal."

But I can't send to bitFlyer's my deposit account address during 3days & still now.
How do I should do?

I want to use My Ledger nano S & Chrome Ledger wallet, send and receice BTC.
That's all now I want.

Please teach me. Please.
My e-mail to LedgerHQ support team, Do you read it? for 4 month ago.
now you do not reply it.

So in here GitHub, please ask some how. :)

my spec data : 

>Chrome for macOS version 62.0.3202.89（Official Build） （64bit）
>macOS version : High Sierra 10.13.1 
>node.js installed. : node-9.1.0.pkg for Mac (64bit)
>npm updated via terminal.
>Ledger nano S : device firmware version 1.3.1 / MCU 1.0
>Ledger Chrome extension wallet version 1.9.3
>using current chain : Bitcoin UASF
>Tx fee level : High (speedy confirm) 
>Sending BTC used MAX deposit button.

>ISP attached network 1) : Wi-Fi (WPA2/AES) > AirMac Time Capsule (5GHz Wi-Fi in house(W52)) 
IP address `fetched` / internet `attached` / DNS server address : `8.8.8.8 / 8.8.4.4` / AP name : `stealth mode`.
>mobile wireless Wi-Fi router net attached network 2) : NEC Aterm MR05LN using via NTTdocoomo MVNO's ISP  network (5GHz Wi-Fi out of house (W56)) / IP address `fetched` / internet `attached` (Ledger Chrome wallet for Bitcoin `loaded my received/sent Txs histories`. But `Not to Send BTCs` from my Ledger nano S.
>another mobile wireless WiMAX Wi-Fi router 3) : ISP UQ-WiMAX speed Wi-Fi Next WX02 (WiMAX : KDDI hosted UQ-WiMAX corp. mobile high speed Wireless network in JP) : same as 2) above. / IP address `fetched` / internet `attached` (Ledger Chrome wallet for Bitcoin `loaded my received/sent Txs histories`. But `Not to Send BTCs` from my Ledger nano S.

**Comment by takeratta** [comment]
I changed node.js version : node-8.8.0.pkg because of npm not suport node-9.1.0.pkg.
And checked erroratta : almost equal as 
>[npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue #13323](https://github.com/npm/npm/issues/13323)

**Comment by takeratta** [comment]
1st trial : to want to use Ledger Chrome wallet Tx fee autocalc & send BTC MAX button enable, & check Ledger nano S + Ledger Chrome wallet.

>install node.js Current version Latest version.9.1.0
>Installed & check : Tx fee autocalc function is OK, & send BTC MAX button : return to change enable.

2nd trial : uninstall node.js+npm (crean up their dependencies manually)
>ref : [How do I completely uninstall Node.js, and reinstall from beginning (Mac OS X)](https://stackoverflow.com/questions/11177954/how-do-i-completely-uninstall-node-js-and-reinstall-from-beginning-mac-os-x)

>EDIT:
>
>You may need to do the additional instructions as well:
>
>`sudo rm -rf /usr/local/{lib/node{,/.npm,_modules},bin,share/man}/{npm*,node*,man1/node*}`
>which is the equivalent of (same as above)...
>
>`sudo rm -rf /usr/local/bin/npm /usr/local/share/man/man1/node* /usr/local/lib/dtrace`

i removed step by step : 
>open terminal
>$ `node -v`
>v9.1.0
>$ `npm -v`
>5.5.1

checked dependencies : 
>$ `npm ls -g --depth=0`

>npm WARN npm npm does not support Node.js v9.1.0
>npm WARN npm You should probably upgrade to a newer version of node as we
>npm WARN npm can't make any promises that npm will work with this version.
>npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8.
>npm WARN npm You can find the latest version at https://nodejs.org/
>/usr/local/lib
>├── grunt-cli@1.2.0
>├── gulp@3.9.1
>├── minimatch@3.0.2
>├── npm@5.5.1
>├── sparkly-cli@1.2.0
>├── to@0.2.9
>├── update@0.7.4
>└── vue-cli@2.9.1

Then, WARNINGs are omit.
Next removed  grunt-cli, gulp,  minimatch, sparkly-cli, to,  vue-cli,  update & npm.
>$ `npm uninstall -g grunt-cli`
>npm WARN npm npm does not support Node.js v9.1.0
>npm WARN npm You should probably upgrade to a newer version of node as we
>npm WARN npm can't make any promises that npm will work with this version.
>npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8.
>npm WARN npm You can find the latest version at https://nodejs.org/
>removed 16 packages in 0.346s

>$` npm uninstall -g gulp`
>npm WARN npm npm does not support Node.js v9.1.0
>npm WARN npm You should (omit)
>npm WARN npm You can find the latest version at https://nodejs.org/
>removed 186 packages in 1.777s

>$ `npm uninstall -g sparkly-cli`
> (WARNINGs omit)
>removed 47 packages in 0.542s

>$ `npm uninstall -g to`
>(WARNINGs same above : omit)
>removed 11 packages in 0.295s

>$ `npm uninstall -g vue-cli`

>$ `npm uninstall -g update`

>$  `npm uninstall -g npm`

And checked dependencies.
>$ `npm ls -g --depth=0`
>-bash: npm: command not found

now `exit` sudo, & 
>$ `brew doctor`

knew some dir not to remove : npm, node, node_module.
using "`sudo`" command (when remove ".npm" file)
To completely uninstall node + npm is to do the following:

>go to` /usr/local/lib` and delete any `node` and `node_modules`
>go to` /usr/local/include` and delete any `node` and `node_modules` directory
>if you installed with `brew install node`, then run `brew uninstall node` in your terminal
>check `your Home directory` for any `local` or `lib` or` include` folders, and delete any `node` or `node_modules` from there
>go to `/usr/local/bin` and delete any `node` executable

>47 Thanks for the detailed instruction, I add to additionally >remove:` /usr/local/bin/npm/usr/local/share/man/man1/node.1` `/usr/local/lib/dtrace/node.d` -
 ngeek Sep 13 '13 at 8:02 
>22 I also had to `rm -rf /Users/[homedir]/.npm`. – brokenindexfinger Apr 18 '14 at 17:05 
>90 I wish node had a built-in cleanup tool or something. – Chev Jul 29 '14 at 3:47
>6 I also ran `brew doctor` and then `brew prune` to clean up a bunch of broken symlinks for >NPM. – Chris Jacob Sep 2 '14 at 11:54
>30 I threw together a script that I've now battle tested. >Thanks @DominicTancredi this works great! [gist.github.com/brock/5b1b70590e1171c4ab54](gist.github.com/brock/5b1b70590e1171c4ab54) – brock Sep 13 '14 at 1:50

3rd trial : No dependencies, went https://nodejs.org/en/ 
downloaded & Re-Installed node.js current latest version node-9.1.0.pkg (including npm version 5.5.1 / no support to node.js).
The pkg file was downloaded & opened & installed node.js again.

>open terminal.
>$ `node -v`
>v9.1.0
>$ npm -v
>5.5.1
>$ `npm update`

And checked Ledger Chrome wallet would be able to send my BTC.

`Ledger Chrome Wallet app` open & try to send BTC to bitFlyer my deposit address.
>set Tx fee level : `high (speedy confirm)` / sending BTC `MAX` button used(clicked).
>And click send button, But `Send Error`.

I'm a silly guy...
**Anyone help !**

**Comment by takeratta** [comment]
4th trial : 

open terminal.
>$ `gulp --help`
>[15:36:22] Local gulp not found in /Users/[username]
>[15:36:22] Try running: npm install gulp

so tried to install gulp.
>$ `npm install -g gulp`
> to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
>npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
>/usr/local/bin/gulp -> /usr/local/lib/node_modules/gulp/bin/gulp.js
>+ gulp@3.9.1
>updated 1 package in 10.194s

npm WARNING dependency of `minimatc`h's version `errortta again`.
>$ `npm i -D gulp@3.9.1`
>npm WARN saveError ENOENT: no such file or directory, open '/Users/tar2/package.json'
>npm WARN enoent ENOENT: no such file or directory, open '/Users/tar2/package.json'
>npm WARN tar2 No description
>npm WARN tar2 No repository field.
>npm WARN tar2 No README data
>npm WARN tar2 No license field.
>
>+ gulp@3.9.1
>added 230 packages in 58.612s

tried to npm cache clean.
>$ n`pm cache clean --force`
>npm ERR! As of npm@5, the npm cache self-heals from corruption issues and data extracted frnpm WARN using --force I sure hope you know what you are doing.

tried to check npm & node.js version.
>$ `npm --version`
>5.5.1

>$ `node -v`
>v8.9.1

tried command via Ledger's install manual : 
>$ `gulp --help`
>[15:59:23] No gulpfile found

gulp was installed but command `guip` --help said `No gulpfile found`. why?

**Comment by takeratta** [comment]
5th trial : 

>1.  I tried to check npm permissions.
>     ref : [Fixing npm permissions :: [npmjs.com](npmjs.com)](https://docs.npmjs.com/getting-started/fixing-npm-permissions)
Finaly I tried `Option 3: Use a package manager that takes care of this for you.`
>$ `brew install node`
>$ `node -v`
> v8.9.1

I can open Ledger Chrome Wallet for Bitcoin, but can't Tx fee autocalc level : `high ONLY disable`, BTC MAX button : `disable` /
Tx fee autocalc `normal, low & custom level : autocalc : OK` / sending BTC : `Tx fee level (ALL)` : `sending error , Try later...`

>2. Change using my Mac using machines : from `MacBook Air 13"` to `MacBook Pro 15"`

same as 5th trial 1) : `sending error / try later...`

>3.I tried to `uninstalled` & `re-installed` Chrome current latest version browsers . (execept `.plist` file for Chrome's my environment files syncing Google my account. 
(I afraid if my Ledger wallet address could change w/ `BIP44 Path`. then I would n`ot to access and open my BTCs`, so I except `.pfile` to keep and avoid my BTC lost accident.)

same as 5th trial 1) : `sending error / try later...`

why ? Any other idea if you have, Please help me...

**Comment by pollastri-pierre** [comment]
Hi, I will need some information to understand the problem here. If you are referring to the bitcoin chrome application we don't have anything like "Sender Name", we are just displaying addresses or 
"coinbase" (which is not related to the exchange company, but it's a reference to the coinbase transaction https://bitcoin.org/en/glossary/coinbase). But it may be a bug since coinbase transaction are really rare so I will need the transaction hash of this transaction in order to understand.

For the second issue, I will need the logs of your application right after the bug occurs. Please try to reset application data before sending me these details (you can do it by clicking on Settings > Tools > Reset application data).

Once you tried to reset the data, and reproduce the bug please send me the transaction hash and your logs to pierre@ledger.fr

**Comment by takeratta** [comment]
Thanks ! @pollastri-pierre 
I'll try to reset my Ledger nano S and check transaction hash.
