### ISSUE TITLE
[feature request] Native app (eg Electron?)

### ISSUE THREAD

**Issue by briannyeko** [LedgerHQ/ledger-wallet-chrome#64]
Google will restrict their chrome apps to only run Chrome notebooks(notebooks running Chrome OS) Ending Windows/Mac support for chrome apps, link: (https://www.windowscentral.com/chrome-apps-support-windows-will-end-2018)
 https://blog.chromium.org/2016/08/from-chrome-apps-to-web.html

By replacing the chrome app with a Native app(Electron) before the support ends, anyone will be able to use your app(Linux, Windows & Mac). When will you offer a Native app for the ledger chrome wallet?

**Comment by pollastri-pierre** [comment]
No ETA yet, we are still working on it. If we are not ready to release the new application once Google removed Chrome apps from their store, we will release a electron based version of our current apps (those apps are already working).
