### ISSUE TITLE
[feature request] Firefox/Brave Browser support

### ISSUE THREAD

**Issue by briannyeko** [LedgerHQ/ledger-wallet-chrome#65]
I want to use the ledger wallet(Nano S/Blue) with myetherwallet, when will you offer it for individuals running Firefox/brave?

**Comment by pollastri-pierre** [comment]
For MEW this doesn't depends on us. MEW is already working on Firefox with a Fido U2F plugin. The Nano S/Blue is supported by every single browser supporting Fido U2F.
