### ISSUE TITLE
Building the application for another coin

### ISSUE THREAD

**Issue by iinstances** [LedgerHQ/ledger-wallet-chrome#79]
I'm testiing my old **HW.1** wallet trying to build the app for another coin but the filename of the new extension is the same that for Bitcoin. Adding it to Chrome doesn't apparently differenciate with the previous **Bitcoin** version. And running the new app, get stuck **synchronizing**. Furhermore it still ask for Bitcoin or BitcoinCash after the PIN.

Is it really doable to build this app for another coin? I'm testing it for the **Bitcoin-Tesnet** and **Litecoin-testnet** chains.

Thank in advance.

**Comment by pollastri-pierre** [comment]
Hi, unfortunately you can only use Bitcoin and BCH with the HW1.
