### ISSUE TITLE
Does not build [Win7]

### ISSUE THREAD

**Issue by sbuergel** [LedgerHQ/ledger-wallet-chrome#8]
Hi all

Unfortunately I cannot build as described. I setup a clean node.js environment on Windows 7, setup the build environment successfully as described (thanks for the hints!). When running:

    gulp clean build package --release

I receive the following error messages:

    [22:28:52] Using gulpfile ~\Downloads\ledger-wallet-chrome\gulpfile.js
    [22:28:52] Starting 'clean'...
    [22:28:52] Starting 'build'...
    [22:28:52] Starting 'package'...
    [22:28:52] Finished 'clean' after 109 ms
    [...]\Downloads\ledger-wallet-chrome\compilation\gulp-flavors.coffee:36
        _ref1 = file.path.match(/.+\/(.+)$/), __ = _ref1[0], filename = _ref1[1];
                                                        ^
    TypeError: Cannot read property '0' of null

Could very well be my mistake. Any help would be appreciated!

**Comment by pollastri-pierre** [comment]
Hi,

I found the problem, it was due to Windows path separators. We never tested compilation on Windows until now ;). You can pull the master branch and run `npm install` to update node modules. The application compiles now though a bug remains related to less files compilation. The application is working but looks ugly. I'm still looking for a fix apparently this is caused by the 'gulp-less' plugin.

**Comment by pollastri-pierre** [comment]
After updating gulp-less to its latest version, everything seems to be alright. Just run `npm update` after pulling the master branch and all should be ok.

**Comment by sbuergel** [comment]
Hi

Thanks for looking into this, now it builds without errors. However, I do not see any output file (crx) upon running

    gulp clean build package --release

I also tried a simple

    gulp package --release

but it also did not create anything.

You write
>This will create a crx file into the dist directory.

There are two issues with that:
1. I do not see any dist directory in the main folder. I assume you mean "compilation\dist"?
2. The above mentioned folder is empty after the build.

I would be happy if you could resolve this one as well! Thanks!

**Comment by pollastri-pierre** [comment]
Hi,

This should work now ;). The dist/signature directories created in the compilation folder was a bug. You should see the dist directory in the root dir of the repo.

**Comment by sbuergel** [comment]
Thanks for your responsiveness and fixing this. Seems to be all working now!
