### ISSUE TITLE
BCH sent to main chain using Wallet and now it wont move

### ISSUE THREAD

**Issue by 4Reallive** [LedgerHQ/ledger-wallet-chrome#87]
i have sent BCH into my 'ledger nano s' wallet and sent it to the MAIN chain (I have since learned it should be sent to the split chain).

The balance appears in the my BCH main account and so i thought it was ok and i have left it for a couple of months.

Today i have tried to move the funds and after i verify the transaction on my Ledger Nano S i am shown a sending error on the wallet app. I have tried to send into many different destination addresses with no success.

So is my Bitcoin Cash on the BTC chain (main)? I can see it, can it be recovered? 
If i can see the funds why cant i move them?

**Comment by 4Reallive** [comment]
So looking around it seems that i have sent my BCH to the BTC main chain.

I am considering using the features of exodus to recover the coins, See below article

http://support.exodus.io/article/189-ive-sent-bitcoin-cash-to-my-bitcoin-address

In order for this to work I will need to convert the Ledger mnemonic seed (25 word) into a 12 word and restore into Exodus and scan the chain.

Please provide feedback as this is a tricky problem to be in.

If anyone has any other ideas Please assist. I am very good with the technical side of things and am quite capable.

**Comment by 4Reallive** [comment]
I am planning on using this website to convert the 24 word key into 12 and restoring it onto Eluctrum

using this converter

https://iancoleman.io/bip39/

(The conversion will be performed on an dedicated offline PC and once restored, emptied)

**Comment by 4Reallive** [comment]
I can send ScreenShots if required to clarify anything

**Comment by 4Reallive** [comment]
The transactions were both send to addresses beginning with 1 on the MAIN chain. (NOT THE SPLIT CHAIN)

Please advise why it cannot be moved off the MAIN chain.

**Comment by amougel** [comment]
Github is only to be used for development issues. Please contact our support or use our forum here: https://support.ledgerwallet.com/hc/en-us

**Comment by 4Reallive** [comment]
Thank you @amougel for your response.
I did submit there first. Apologies as you can understand this is not a great position for me.

I will await a response, i too think it is a simple problem, i will await advice from Ledger before trying anything myself.

Happy coding
