### ISSUE TITLE
Ledger Wallet Self-Opens

### ISSUE THREAD

**Issue by droplister** [LedgerHQ/ledger-wallet-chrome#9]
So, maybe it's not "self opening", but I've been having this issue where randomly Ledger wallet will pop up. I do not know what causes it to do this, but it's happened a few times now. And each time I just uninstall the extension. I can't help you replicate this error locally, but it is an issue I have encountered. It may be related to malware even.

**Comment by pollastri-pierre** [comment]
Hi, 

The application can be open on a website page using the Chrome app API. Do you remember if you had an open page using the chrome app api when you had the problem ?
